import os
from dotenv import load_dotenv

load_dotenv()

INFLUXDB_URL = os.getenv("INFLUXDB_URL", "http://localhost:8086")
INFLUXDB_TOKEN = os.getenv("INFLUXDB_TOKEN", "iptv-monitor-super-secret-token-2024")
INFLUXDB_ORG = os.getenv("INFLUXDB_ORG", "iptv")
INFLUXDB_BUCKET = os.getenv("INFLUXDB_BUCKET", "metrics")

REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379")
SQLITE_PATH = os.getenv("SQLITE_PATH", "/data/db/iptv.db")
THUMBNAIL_DIR = os.getenv("THUMBNAIL_DIR", "/data/thumbnails")
SIM_VIDEO_DIR = os.getenv("SIM_VIDEO_DIR", "/data/videos")

WORKER_COUNT = int(os.getenv("WORKER_COUNT", "10"))
CHANNELS_PER_WORKER = int(os.getenv("CHANNELS_PER_WORKER", "30"))

UDP_RECV_BUFFER = 4 * 1024 * 1024
UDP_TIMEOUT_SEC = 5.0

BLACK_LUMA_THRESHOLD = 16
FREEZE_MSE_THRESHOLD = 0.5
FREEZE_DURATION_SEC = 10
FRAME_SAMPLE_INTERVAL_SEC = 5

SILENCE_RMS_THRESHOLD = 0.001
SILENCE_DURATION_SEC = 5
CLIP_THRESHOLD = 0.98
CLIP_RATIO_THRESHOLD = 0.01

CC_ERROR_THRESHOLD = 5
PCR_JITTER_THRESHOLD_MS = 40.0
BITRATE_DEVIATION_THRESHOLD = 0.3

INFLUX_BATCH_SIZE = 300
INFLUX_FLUSH_INTERVAL_MS = 1000

THUMBNAIL_WIDTH = 320
THUMBNAIL_HEIGHT = 180
THUMBNAIL_QUALITY = 75
